services:
  crypto-signal-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_signal_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
